import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths"
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const host = process.env.TAURI_DEV_HOST;

// 哥特加载页 HTML（构建 / 开发时由 Vite 插件内联进 index.html，消除外部脚本依赖）
const root = process.cwd();
const lightPageHtml = readFileSync(resolve(root, "wait-page/waiting-page-light.html"), "utf-8");
const darkPageHtml  = readFileSync(resolve(root, "wait-page/waiting-page-dark.html"), "utf-8");
const LIGHT_B64 = Buffer.from(lightPageHtml).toString("base64");
const DARK_B64  = Buffer.from(darkPageHtml).toString("base64");

// 把两份 base64 落盘成 TS 模块，供 bootPreview.ts 导入。
// 关键：关于→预览此前用 `?raw` 导入 wait-page 的 .html，但 Vite 生产构建会把 .html 当成
// HTML 入口拦截、`?raw` 静默失效（dev 正常），导致打包后预览内容为空。该生成模块绕开此坑，
// 且与 index.html 启动页共用同一份经校验的 base64，单一可信源。
const GENERATED = resolve(root, "src/lib/_waitingPages.generated.ts");
writeFileSync(
  GENERATED,
  `// AUTO-GENERATED by vite.config.ts — 请勿手动编辑；由 wait-page/*.html 构建期生成。\n` +
  `export const WAITING_LIGHT_B64 = ${JSON.stringify(LIGHT_B64)};\n` +
  `export const WAITING_DARK_B64 = ${JSON.stringify(DARK_B64)};\n`
);

// https://vite.dev/config/
export default defineConfig(() => ({
  base: "./",
  plugins: [
    react(),
    tsconfigPaths(),
    {
      name: "inject-waiting-pages",
      transformIndexHtml: {
        order: 'pre',
        handler(html: string) {
          return html
            .replace("___WAITING_LIGHT_B64___", LIGHT_B64)
            .replace("___WAITING_DARK_B64___",  DARK_B64);
        },
      },
    },
  ],

    // === 强制去重 react / react-dom ===
  resolve: {
    dedupe: ["react", "react-dom"],
  },

  // === 预构建时明确包含它们，防止遗漏 ===
  optimizeDeps: {
    include: ["react", "react-dom"],
  },

  // === 多页入口：截图覆盖窗使用独立轻量 HTML（不加载主应用），实现「秒开」 ===
  build: {
    // 把体积较大的第三方库拆成独立、可缓存的 vendor chunk，避免单个 main chunk 超过 500KB 警告，
    // 同时让浏览器可并行拉取、长期缓存。富文本编辑器（TipTap/prosemirror）已通过 React.lazy
    // 动态导入单独成 chunk，这里不再手动归并它，避免破坏懒加载边界。
    chunkSizeWarningLimit: 600,
    rollupOptions: {
      input: {
        main: "index.html",
        "screenshot-overlay": "screenshot-overlay.html",
        "recorder-widget": "recorder-widget.html",
        "recorder-select": "recorder-select.html",
        "recording-border": "recording-border.html",
        "deskpet": "deskpet.html",
      },
      output: {
        manualChunks(id: string) {
          if (id.includes('node_modules')) {
            if (id.includes('lucide-react')) return 'icons';
            // 只精确匹配 React 核心包（react / react-dom / scheduler），避免误吞 @tiptap/react、
            // @radix-ui/react-* 等名字里带 react 的库，否则它们会被提前打进 eager 的 react-vendor，
            // 既撑大首屏又破坏富文本编辑器的懒加载边界。
            if (/[\\/]node_modules[\\/](react|react-dom|scheduler|use-sync-external-store)[\\/]/.test(id)) return 'react-vendor';
            if (id.includes('@radix-ui')) return 'radix';
            if (id.includes('@tauri-apps')) return 'tauri-vendor';
          }
        },
      },
    },
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: 1421,
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
